apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webmasterbrief
  labels:
    app: webmasterbrief
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: webmasterbrief
        service: web
    spec:
      containers:
        - name: webmasterbrief
          image: lrhstsa/webmasterbrief:2.0.1
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webmasterbrief
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: webmasterbrief
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webmasterbrief
  labels:
    service: web
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - brief.lrhstsa.com
      secretName: webmasterbrief-tls
  rules:
    - host: brief.lrhstsa.com
      http:
        paths:
          - path: /
            backend:
              serviceName: webmasterbrief
              servicePort: 80
