apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webmasterchapter
  labels:
    app: webmasterchapter
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: webmasterchapter
        service: web
    spec:
      containers:
        - name: webmasterchapter
          image: lrhstsa/webmasterchapter:2.0.1
          ports:
            - containerPort: 5000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webmasterchapter
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: webmasterchapter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webmasterchapter
  labels:
    service: web
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - lrhstsa.com
      secretName: webmasterchapter-tls
  rules:
    - host: lrhstsa.com
      http:
        paths:
          - path: /
            backend:
              serviceName: webmasterchapter
              servicePort: 80
