apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
  labels:
    app: memcached
    role: cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
        role: cache
    spec:
      containers:
        - name: memcached
          image: memcached:1.4.34-alpine
          ports:
            - containerPort: 11211
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    role: cache
spec:
  ports:
    - port: 11211
      protocol: TCP
      name: memcached
  selector:
    app: memcached
