apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dovecot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dovecot
        version: 1.2.0
    spec:
      containers:
      - name: dovecot
        image: realmic/dovecot:1.2.0
        ports:
        - containerPort: 143
          protocol: TCP
        - containerPort: 4190
          protocol: TCP
        - containerPort: 12345
          protocol: TCP
        - containerPort: 24
          protocol: TCP
        volumeMounts:
        - mountPath: /var/mail
          name: mail
        - mountPath: /etc/dovecot/ssl
          name: ssl
        - mountPath: /etc/dovecot/sql
          name: sql
      volumes:
      - name: mail
        glusterfs:
          endpoints: glusterfs
          path: mail
          readOnly: false
      - name: ssl
        secret:
          secretName: prod-tls
      - name: sql
        secret:
          secretName: dovecot
---
apiVersion: v1
kind: Service
metadata:
  name: dovecot-public
  labels:
    app: dovecot
    version: 1.2.0
spec:
  ports:
  - port: 143
    protocol: TCP
    name: imap
  - port: 4190
    protocol: TCP
    name: managesieve
  selector:
    app: dovecot
    version: 1.2.0
  externalIPs:
    - 192.169.7.138
---
apiVersion: v1
kind: Service
metadata:
  name: dovecot
  labels:
    app: dovecot
    version: 1.2.0
spec:
  ports:
  - port: 24
    protocol: TCP
    name: lmtp
  - port: 12345
    protocol: TCP
    name: sasl
  selector:
    app: dovecot
    version: 1.2.0
