apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: teamspeak3
  labels:
    app: teamspeak3
    service: voice
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: teamspeak3
        service: voice
    spec:
      containers:
        - name: teamspeak3
          image: luzifer/teamspeak3:3.0.13.4
          ports:
            - containerPort: 9987
              protocol: UDP
            - containerPort: 30033
              protocol: TCP
          volumeMounts:
            - mountPath: /teamspeak3
              name: teamspeak3
      volumes:
        - name: teamspeak3
          persistentVolumeClaim:
            claimName: teamspeak3
---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak3
  labels:
    service: voice
spec:
  ports:
    - port: 9987
      protocol: UDP
      name: tsvoice
    - port: 30033
      protocol: TCP
      name: tsfiles
  selector:
    app: teamspeak3
  externalIPs:
    - 10.0.0.6
