apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prod
  labels:
    service: web
  annotations:
    kubernetes.io/tls-acme: true
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - prod.mctherealm.net
      secretName: prod-tls
  rules:
    - host: prod.mctherealm.net
      http:
        paths:
          - path: /
            backend:
              serviceName: default-http-backend
              servicePort: 80
