apiVersion: "v1"
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    name: jenkins
  ports:
  - port: 8080
    name: http
    protocol: TCP
  - port: 50000
    name: slave
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - jenkins.mctherealm.net
    secretName: jenkins-tls
  rules:
  - host: jenkins.mctherealm.net
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
