apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    role: database
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: mariadb
        role: database
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.1.21
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    role: database
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: sql
  selector:
    app: mariadb
