apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lakewoodleaders
  labels:
    app: lakewoodleaders
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: lakewoodleaders
        service: web
    spec:
      containers:
        - name: lakewoodleaders
          image: realmicprojects/lakewoodleaders:0.8.2
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: mysql-database
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: mysql-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: mysql-password
            - name: RECAPTCHA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: recaptcha-public-key
            - name: RECAPTCHA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: recaptcha-private-key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: secret-key-base
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lakewoodleaders
                  key: mail-password
          ports:
            - containerPort: 9292
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lakewoodleaders
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 9292
      protocol: TCP
      name: http
  selector:
    app: lakewoodleaders
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lakewoodleaders
  labels:
    service: web
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - leaders.lrhsclubs.com
      secretName: lakewoodleaders-tls
  rules:
    - host: leaders.lrhsclubs.com
      http:
        paths:
          - path: /
            backend:
              serviceName: lakewoodleaders
              servicePort: 80
