apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs
  labels:
    app: gogs
    service: git
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gogs
        service: git
    spec:
      containers:
        - name: gogs
          image: gogs/gogs:0.9.97
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: gogs
      volumes:
        - name: gogs
          persistentVolumeClaim:
            claimName: gogs
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    service: git
spec:
  ports:
    - port: 22
      protocol: TCP
      name: ssh
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: gogs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
  labels:
    service: git
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - git.mctherealm.net
      secretName: gogs-tls
  rules:
    - host: git.mctherealm.net
      http:
        paths:
          - path: /
            backend:
              serviceName: gogs
              servicePort: 80
