apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs
  labels:
    app: gogs
    service: git
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gogs
        service: git
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
            "name": "setup",
            "image": "realmic/rsync:1.1.0",
            "command": ["rsync", "-a", "--delete", "/mnt/gluster/", "/mnt/local/"],
            "volumeMounts": [
              {
                "name": "gogs",
                "mountPath": "/mnt/gluster"
              },
              {
                "name": "local",
                "mountPath": "/mnt/local"
              }
            ]
          }
        ]'
    spec:
      containers:
        - name: gogs
          image: gogs/gogs:0.9.97
          ports:
            - containerPort: 22
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: local
        - name: data-transfer
          image: realmic/rsync:1.1.0
          command: ["lsyncd", "-nodaemon", "-rsync", "/mnt/local", "/mnt/gluster"]
        volumeMounts:
          - mountPath: /mnt/gluster
            name: gogs
          - mountPath: /mnt/local
            name: local
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "20"]
      volumes:
        - name: gogs
          glusterfs:
            endpoints: glusterfs
            path: gogs
            readOnly: false
        - name: local
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gogs-ssh
  labels:
    service: git
spec:
  ports:
    - port: 22
      protocol: TCP
      name: ssh
  selector:
    app: gogs
  externalIPs:
    - 192.169.7.138
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    service: git
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: gogs
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gogs
  labels:
    service: git
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - git.mctherealm.net
      secretName: gogs-tls
  rules:
    - host: git.mctherealm.net
      http:
        paths:
          - path: /
            backend:
              serviceName: gogs
              servicePort: 80
